# Generated by Django 4.0.3 on 2022-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('dateUpdated', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
